plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-3.3.0.cjs
nodeLinker: node-modules

packageExtensions:
  '@nestjs/common@*':
    dependencies:
      '@types/node': '*'
      '@nestjs/common': '*'
  '@nestjs/axios@*':
    dependencies:
      '@nestjs/common': '*'
      '@types/node': '*'
  swagger-ui-express@*:
    dependencies:
      '@types/node': '*'
  '@nestjs/apollo@*':
    dependencies:
      apollo-server-core: '*'
      apollo-server-express: '*'
      graphql: '*'
      '@nestjs/apollo': '*'
      '@nestjs/common': '*'
      '@nestjs/graphql': '*'
  apollo-server-express@*:
    dependencies:
      '@nestjs/apollo': '*'
      apollo-server-core: '*'
      '@types/express': '*'
