services:
  nest:
    container_name: animal_gram
    restart: always
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./packages/server:/app/packages/server
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    working_dir: /app/packages/server
    command: yarn run server:start:dev
    networks:
      - animal_gram_net
    depends_on:
      - redis-master
      - postgres

  postgres:
    container_name: animal_gram_db
    image: postgres
    env_file: .env
    networks:
      - animal_gram_net
    volumes:
      - animalgramdbdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis-master:
    hostname: redis-master
    container_name: redis-master
    image: bitnami/redis:latest
    environment:
      - REDIS_REPLICATION_MODE=master
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    networks:
      - animal_gram_net

  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: test
    networks:
      - animal_gram_net

networks:
  animal_gram_net:
volumes:
  animalgramdbdata:
